version: '3'
services:
  mysql:
    image: mysql:8.0
    networks:
      - dashboard_network
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    ports:
      - "13306:3306"
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw

  dashboard-member-service:
    image: dashboard-member-service:1.0.0
    networks:
      - dashboard_network
    ports:
      - "8061:8061"
    depends_on:
      - mysql
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  dashboard-front-service:
    image: dashboard-front-service:0.0.1
    networks:
      - dashboard_network
    ports:
      - "8062:8062"
    depends_on:
      - mysql
    environment:
      - SPRING_PROFILES_ACTIVE=docker

networks:
  dashboard_network:
    driver: bridge