feign:
  url:
    member-service: localhost:8071/member
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 3000
        loggerLevel: NONE
      post-command:
        connectTimeout: 1000
        readTimeout: 10000
        loggerLevel: HEADERS