apiVersion: apps/v1
kind: Deployment
metadata:
  name: member
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: member
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"